#
# This source file is part of the Stanford XCTestExtensions open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildandtest_ios:
    name: Build and Test Swift Package iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: XCTestExtensions-Package
      resultBundle: XCTestExtensions-iOS.xcresult
      artifactname: XCTestExtensions-iOS.xcresult
  buildandtest_watchos:
    name: Build and Test Swift Package watchOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: XCTestExtensions-Package
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)'
      resultBundle: XCTestExtensions-watchOS.xcresult
      artifactname: XCTestExtensions-watchOS.xcresult
  buildandtest_visionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: XCTestExtensions-Package
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: XCTestExtensions-visionOS.xcresult
      artifactname: XCTestExtensions-visionOS.xcresult
  buildandtest_macos:
    name: Build and Test Swift Package macOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: XCTestExtensions-Package
      destination: 'platform=macOS,arch=arm64'
      resultBundle: XCTestExtensions-macOS.xcresult
      artifactname: XCTestExtensions-macOS.xcresult
  buildandtestuitests_ios:
    name: Build and Test UI Tests iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: Tests/UITests
      scheme: TestApp
      resultBundle: TestApp-iOS.xcresult
      artifactname: TestApp-iOS.xcresult
  buildandtestuitests_visionos:
    name: Build and Test UI Tests visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: Tests/UITests
      scheme: TestApp
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: TestApp-visionOS.xcresult
      artifactname: TestApp-visionOS.xcresult
  buildandtestuitests_macos:
    name: Build and Test UI Tests macOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: Tests/UITests
      scheme: TestApp
      destination: 'platform=macOS,arch=arm64'
      resultBundle: TestApp-macOS.xcresult
      artifactname: TestApp-macOS.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest_ios, buildandtest_visionos, buildandtest_watchos, buildandtest_tvos, buildandtest_macos, buildandtestuitests_ios, buildandtestuitests_visionos, buildandtestuitests_macos]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: XCTestExtensions-iOS.xcresult XCTestExtensions-watchOS.xcresult XCTestExtensions-visionOS.xcresult XCTestExtensions-tvOS.xcresult XCTestExtensions-macOS.xcresult TestApp-iOS.xcresult TestApp-visionOS.xcresult TestApp-macOS.xcresult
